# Configuração do servidor Nginx que serve o frontend estático.
server {
    # Porta interna onde o Nginx fica à escuta dentro do container.
  listen 80;
  server_name localhost;

    # Oculta a versão do Nginx nos headers HTTP.
  server_tokens off;

    # Diretoria onde ficam os ficheiros estáticos da aplicação.
  root /usr/share/nginx/html;
  index main_page.html;

  location ~* \.(?:html|js|css)$ {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
    try_files $uri =404;
  }

    # Encaminha pedidos para ficheiros estáticos existentes ou para a página principal.
  location / {
    try_files $uri $uri/ =404;
  }
}
