# Define a imagem base usada pelo container.
FROM nginx:latest
# Copia ficheiros da aplicação para a imagem.
COPY ./public /usr/share/nginx/html
# Copia ficheiros da aplicação para a imagem.
COPY config.conf /etc/nginx/conf.d/default.conf
